### ISSUE TITLE
Become Eire overlord decision relys on not being a secondary power

### ISSUE THREAD

**Issue by Spartan322** [Savolainen5/The-Heirs-to-Aquitania#3]
Is there a reason they need to also not be a secondary power? Like if you puppet them and don't siege everything down for a while, (and likely don't destroy their entire military) you can never call this decision, which doesn't make sense to me.

**Comment by Savolainen5** [comment]
Good points. Have updated the code for that decision so that they're either your vassal, your sphereling, or not a GP/SP/vassal. That plus the existing "you're my vassal or we have less than -150" is enough for now. I'll put it on the list to look at a bit more closely so that it's a bit less convoluted. For more info see my other comment.
